### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by interstar** [SOM-st/CSOM#19]
Just cloned this to have a look at and tried to compile it on my machine by typing "make".

I get 

```
cc -m32 -Wno-endif-labels -std=gnu99  -O3 -I/home/phil/Documents/work/future-office-labs/WCHNT/CSOM/src -fPIC -c /home/phil/Documents/work/future-office-labs/WCHNT/CSOM/src/primitives/System.c -o /home/phil/Documents/work/future-office-labs/WCHNT/CSOM/src/primitives/System.pic.o
In file included from /home/phil/Documents/work/future-office-labs/WCHNT/CSOM/src/primitives/System.c:27:
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
   27 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/home/phil/Documents/work/future-office-labs/WCHNT/CSOM/build/Linux.make:159: /home/phil/Documents/work/future-office-labs/WCHNT/CSOM/src/primitives/System.pic.o] Error 1

```

Obviously some missing dependency, but what is that dependency?

I'm on Ubuntu 20.04

**Comment by smarr** [comment]
@interstar this doesn't look like a CSOM dependency.
In CI we only install this: https://github.com/SOM-st/CSOM/blob/master/.travis.yml#L5
`libc6-dev-i386 gcc-multilib`

Looking at the error, it fails with the include of stdio.h, because some `bits/libc-header-start.h` header does not exist.
This is a dependency of `stdio.h` on your system and unrelated to CSOM.

An a Ubuntu system, I'd normally expect `build-essential` to provide all needed dependencies.
Though, you may need to specify the architecture explicitly. So, instead of `make`, rather `ARCH=64bit make`.

**Comment by smarr** [comment]
Instead of updating the readme, I decided to set the default architecture to 64bit https://github.com/SOM-st/CSOM/pull/20

This might fix your issues. Not sure.

**Comment by interstar** [comment]
Cool. Yeah. That works. (That change to 64bit architecture)..

Thanks.
